version: '3.9'
services:
  php-cli:
    container_name: checkout
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null