<?php

use TestCheckout\Entities\ReducingAmountType;
use TestCheckout\Entities\ReducingOperationType;

return [
    [
        'code'              => 'FR1',
        'name'              => 'Fruit of tea',
        'price'             => 3.11,
        'quantity'          => 2,
        'discountQty'       => 3,
        'discountAmount'    => 75,
        'discountType'      => ReducingAmountType::percentage,
        'discountOperation' => ReducingOperationType::discount,
        'expected'          => 3.11,
    ],
    [
        'code'              => 'FR1',
        'name'              => 'Fruit of tea',
        'price'             => 3.11,
        'quantity'          => 5,
        'discountQty'       => 3,
        'discountAmount'    => 75,
        'discountType'      => ReducingAmountType::percentage,
        'discountOperation' => ReducingOperationType::discount,
        'expected'          => 0.78,
    ],
    [
        'code'              => 'FR1',
        'name'              => 'Fruit of tea',
        'price'             => 3.11,
        'quantity'          => 2,
        'discountQty'       => 3,
        'discountAmount'    => 100,
        'discountType'      => ReducingAmountType::percentage,
        'discountOperation' => ReducingOperationType::discount,
        'expected'          => 3.11,
    ],
    [
        'code'              => 'FR1',
        'name'              => 'Fruit of tea',
        'price'             => 3.11,
        'quantity'          => 2,
        'discountQty'       => 3,
        'discountAmount'    => 2,
        'discountType'      => ReducingAmountType::amount,
        'discountOperation' => ReducingOperationType::discount,
        'expected'          => 3.11,
    ],
    [
        'code'              => 'FR1',
        'name'              => 'Fruit of tea',
        'price'             => 3.11,
        'quantity'          => 5,
        'discountQty'       => 3,
        'discountAmount'    => 2,
        'discountType'      => ReducingAmountType::amount,
        'discountOperation' => ReducingOperationType::discount,
        'expected'          => 1.11,
    ],
    [
        'code'              => 'FR1',
        'name'              => 'Fruit of tea',
        'price'             => 3.11,
        'quantity'          => 2,
        'discountQty'       => 3,
        'discountAmount'    => 2.75,
        'discountType'      => ReducingAmountType::amount,
        'discountOperation' => ReducingOperationType::replacement,
        'expected'          => 3.11,
    ],
    [
        'code'              => 'FR1',
        'name'              => 'Fruit of tea',
        'price'             => 3.11,
        'quantity'          => 2,
        'discountQty'       => 2,
        'discountAmount'    => 50,
        'discountType'      => ReducingAmountType::amount,
        'discountOperation' => ReducingOperationType::replacement,
        'expected'          => 50,
    ],
    [
        'code'              => 'FR1',
        'name'              => 'Fruit of tea',
        'price'             => 3.11,
        'quantity'          => 2,
        'discountQty'       => 3,
        'discountAmount'    => 75,
        'discountType'      => ReducingAmountType::percentage,
        'discountOperation' => ReducingOperationType::replacement,
        'expected'          => 3.11,
    ],
    [
        'code'              => 'FR1',
        'name'              => 'Fruit of tea',
        'price'             => 3.11,
        'quantity'          => 2,
        'discountQty'       => 2,
        'discountAmount'    => 75,
        'discountType'      => ReducingAmountType::percentage,
        'discountOperation' => ReducingOperationType::replacement,
        'expected'          => 2.33,
    ],

];